.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.Dd Dec 23, 2020
.\" Please adjust this date whenever revising the manpage.
.Dt PIMD 8 SMM
.Os
.Sh NAME
.Nm pimd
.Nd PIM-SM/SSM multicast routing daemon
.Sh SYNOPSIS
.Nm pimd
.Op Fl hnrsv
.Op Fl f Ar FILE
.Op Fl d Ar SYS[,SYS,...]
.Op Fl i Ar NAME
.Op Fl p Ar FILE
.Op Fl -disable-vifs
.Op Fl l Ar LEVEL
.Op Fl t Ar ID
.Op Fl u Ar FILE
.Op Fl w Ar SEC
.Sh DESCRIPTION
.Nm
is a stand-alone PIM-SM/SSM multicast routing daemon available under the
free 3-clause BSD license.  This is the restored original from
University of Southern California, by Ahmed Helmy, Rusty Eddy and Pavlin
Ivanov Radoslavov.
.Pp
Protocol Independent Multicast - Sparse Mode (PIM-SM):
.Bl -bullet -width 1n -compact
.It
maintains the traditional IP multicast service model of
receiver-initiated membership
.It
uses explicit joins that propagate hop-by-hop from members' directly
connected routers toward the distribution tree
.It
builds a shared multicast distribution tree centered at a Rendezvous
Point (RP), and then builds source-specific trees for those sources
whose data traffic warrants it
.It
is not dependent on a specific unicast routing protocol, and
.It
uses soft-state mechanisms to adapt to underlying network conditions and
group dynamics
.El
.Pp
The robustness, flexibility, and scaling properties of this architecture
make it well suited to large heterogeneous internetworks.
.Pp
.Nm
originally only implemented RFC2362, but since v2.3.0 is supporting more
and more of RFC4601.
.Pp
.Nm
ships with a
.Xr pimctl 8
tool, which is compatible with all PIM daemon's from the same family:
.Xr pimd 8 ,
.Xr pimd-dense 8 ,
and
.Xr pim6sd .
.Sh OPTIONS
This program follows the usual UNIX command line syntax, with long
options starting with two dashes (`-').  The options are as follows:
.Bl -tag -width Ds
.It Fl h, -help
Print a help message and exit.
.It Fl f, -config Ar FILE
Specify an alternative configuration file, the default
.Pa /etc/pimd.conf ,
is derived from
.Fl -ident Ar NAME ,
which is strongly recommended to use over this option.
.It Fl d, -debug Ar SYS[,SYS...]
This option controls extended subsystem debugging, use
.Cm all
to enable all subsystems.
.Pp
Available subsystems are:
.Pp
.Bl -tag -width pim_routes -compact -offset indent
.It Cm all
All subsystems
.It Cm asserts
PIM assert messages
.It Cm bsr
PIM bootstrap router messages
.It Cm crp
PIM Candidate Rendez-Vous Point messages
.It Cm detail
Detailed PIM debug messages
.It Cm igmp
IGMP messages
.It Cm interfaces
Interface (VIF) debug messages
.It Cm jp
PIM join-prune messages
.It Cm kernel
Kernel messages
.It Cm mfc
Multicast forwarding cache messages
.It Cm mrt
Routing messages
.It Cm neighbors
PIM hello messages to/from neighbors
.It Cm packets
All inbound/outbout packets
.It Cm pim
All PIM messages
.It Cm registers
PIM register tunnel messages
.It Cm rpf
PIM reverse-path forwarding messages
.It Cm rsrr
RSRR messages (if enabled)
.It Cm timers
PIM timer events
.It Cm traceroute
Multicast traceroute information
.El
.It Fl n, -foreground
Run in the foreground, do not detach from calling terminal and do not
fork to background.  Useful not only when debugging (above) but also
when running under a process monitor like daemontools, runit, finit, or
systemd.  Remember to also use
.Fl s ,
to send all logs to the syslog daemon, unless you want to debug
.Nm
and run in the foreground.
.It Fl i, Fl -ident Ar NAME
Specify program identity (name) to be used for configuration file, PID
file and syslog messages.  Useful with multiple instances of
.Nm ,
or to adapt to site specific practices, e.g. "PIM", without renaming the
binary.
.Pp
Note, this option only changes the base name of the files, not the
location, which is system specific.  On most systems this is
.Pa /var/run/pimd.pid ,
or
.Pa /run/pimd.pid ,
and
.Pa /etc/pimd.conf .
.It Fl -disable-vifs
This prevents
.Nm
from running on all interfaces by default.  When this command line
option is given, use
.Cm phyint IFNAME enable
to selectively activate PIM services on an interface.  This command line
option is also available as a setting in the configuration file.
.It Fl p, -pidfile Ar FILE
Set PID file name and location, defaults to
.Pa /var/run/pimd.pid ,
derived from
.Fl -ident Ar NAME ,
which is strongly recommended to change over this option.
.It Fl l, -loglevel Ar LEVEL
Set log level to one of the following, default
.Nm notice :
.Pp
.Bl -tag -width WARNING -compact -offset indent
.It Cm none
Disable all logging
.It Cm error
Error conditions
.It Cm warning
Warning conditions
.It Cm notice
Normal but significant condition (default)
.It Cm info
Informational
.It Cm debug
Debug-level messages
.El
.It Fl r
With this option, and
.Fl -disable-vifs ,
.Nm
will retry (forever) querying the kernel for all required
.Cm phyint
interfaces listed in
.Pa /etc/pimd.conf .
Useful at startup when not all interfaces may be up or have an IP
address assigned yet.
.It Fl s, -syslog
Use syslog, default unless running in foreground,
.Fl n .
.It Fl t, -table-id Ar ID
Set multicast routing table ID.  Remember to also create routing rules
directing packets to the table.  This example uses routing table ID 123:
.Bd -unfilled -offset left
ip mrule add iif eth0 lookup 123
ip mrule add oif eth0 lookup 123
.Ed
.Pp
.Nm Note:
Only available on Linux.
.It Fl u, -ipc Ar FILE
Override UNIX domain socket filename, the default is based on the
identity,
.Fl i Ar NAME .
On most systems this is
.Pa /var/run/pimd.sock .
.It Fl v, -version
Show program version and support information.
.It Fl w, -startup-delay Ar SEC
Initial startup delay of
.Ar SEC
seconds before probing for interfaces.  Useful if
.Nm
starts before interfaces are created and have an IP address.
.El
.Sh TROUBLESHOOTING
.Bl -enum
.It
Check the TTL of incoming multicast.  Remember, the TTL of the multicast
stream must be >1 to be routed.  Or rather, greater than the configured
.Cm ttl-threshold
of the inbound
.Cm phyint ,
see
.Xr pimd.conf 5
for more information.
.It
If you see `Permission denied` in your logs, you are most likely having
firewall, or SELinux, problems
.It
For PIM-SM, make sure you have a Rendezvous-Point (RP) in your
network.  Check the
.Cm rp-candidate
(CRP) and
.Cm bsr-candidate
(CBSR) settings in your
.Xr pimd.conf 5 ,
or
.Cm rp-address
if you prefer the static RP approach
.It
Check the Linux
.Cm rp_filter
sysctl setting.  Many Linux systems have the "strict" setting enabled,
"loose" can work but may cause problems in some setups.  We recommend
disabling the setting entirely
.It
PIM is protocol
.Em independent ,
meaning you must have unicast routing in place already for the multicast
routing decisions made by
.Nm
to work.  Use
.Xr ping 1
to verify connectivity between multicast sender and receiver
.El
.Sh SIGNALS
.Nm
responds to the following signals.  However, consider using
.Nm pimctl
instead since this gives more and better output, and is also less prone
to race conditions.
.Pp
.Bl -tag -width TERM -compact
.It HUP
Restart
.Nm
and reload configuration file
.It TERM
Terminate execution gracefully, i.e. by sending good-bye messages to neighboring
routers
.It INT
The same as TERM
.El
.Pp
For convenience in sending signals,
.Nm
writes its process ID to
.Pa /var/run/pimd.pid
upon startup.  If started with a different identy,
.Fl i Ar NAME ,
then
.Ar NAME
is used as basename of the PID file.
.Sh FILES
The basename of the following files change if
.Nm
is started with a different identity,
.Fl i Ar NAME :
.Pp
.Bl -tag -width /var/run/pimd.sock -compact
.It Pa /etc/pimd.conf
Main configuration file
.It Pa /var/run/pimd.pid
Pidfile (re)created by
.Nm
daemon when it has started up and is ready to receive commands
.It Pa /var/run/pimd.sock
.Ux Ns -domain
socket used for communication with
.Xr pimctl 8
.El
.Sh SEE ALSO
.Xr pimd.conf 5
.Xr pimctl 8 ,
.Xr pimd-dense 8 ,
.Xr pim6sd 8 ,
.Xr mrouted 8 ,
.Xr smcroute 8 ,
.Pp
PIM-SM is described in, the now obsolete RFC2362, and the current
RFC4601, with additions in RFC5059 and RFC5796.
.Pp
The pages at USC, http://netweb.usc.edu/pim/, are unfortunately no
longer available.  The wiki pages at http://github.com/troglobit/pimd/,
the new GitHub project, are an attempt to gather as much info as
possible.
.Sh AUTHORS
.Nm
was originally written by Ahmed Helmy, George Edmond "Rusty" Eddy, and
Pavlin Ivanov Radoslavov.  PIM-SSM, including full IGMPv3 support, was
added by Markus Veranen.  With contributions by many others.
.Pp
This manual page was initially written by Anton\('in Kr\('al for the
Debian GNU/Linux system.  Updated by Joachim Wiberg for the GitHub
.Nm
project.
