.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.Dd $Mdocdate: May 26, 2010 $
.\" Please adjust this date whenever revising the manpage.
.Dt PIMD 8 SMM
.Os
.Sh NAME
.Nm pimd
.Nd PIMv2-SM dynamic multicast routing daemon
.Sh SYNOPSIS
.Nm pimd
.Op Fl fhN
.Op Fl c Ar file
.Op Fl d Op Ar level[,level...]
.Sh DESCRIPTION
.Nm
is the original USC implementation of the PIM-SM dynamic multicast routing protocol.
Protocol Independent Multicast - Sparse Mode,
.Nm
complies with version 2 of the protocol, which is in wide use today and is the
multicast routing protocol used in many proprietary routers.
.Pp
The PIM-SM architecture:
.Bl -bullet -compact
.It
maintains the traditional IP multicast service model of receiver-initiated membership;
.It
uses explicit joins that propagate hop-by-hop from members' directly connected
routers toward the distribution tree.
.It
builds a shared multicast distribution tree centered at a Rendezvous Point, and then
builds source-specific trees for those sources whose data traffic warrants it.
.It
is not dependent on a specific unicast routing protocol; and
.It
uses soft-state mechanisms to adapt to underlying network conditions and group
dynamics.
.El
.Pp
The robustness, flexibility, and scaling properties of this architecture make it well
suited to large heterogeneous internetworks.

.Sh OPTIONS
This program follows the usual UNIX command line syntax, with long options starting
with two dashes (`-').  The options are as follows:
.Bl -tag -width Ds
.It Fl h
Print a help message and exit.
.It Fl c, -config=FILE
Specify an alternative configuration file, instead of the default
.Pa /etc/pimd.conf .
.It Fl d, -debug[=level[,level...]
By default,
.Nm
detaches from the invoking terminal.
If this option is specified,
.Nm
it runs in foreground of the starting terminal and responds to signals.
If
.Fl d
is given with no argument, the debug level defaults to
.Nm igmp, cache, interface, groups, prunes, routes and peers .

Regardless of the debug level,
.Nm
always writes warning and error messages to the system log daemon.
Debug levels have the following effects:
.Pp
.Bl -tag -compact -offset indent
.It packet
Debug inbound/outbout packets
.It prunes
Pruning operations, or pruned routes
.It routes
Routing messages
.It rtdetail
Detailed routing information
.It peers
Neighbor gossip
.It cache
Debug routing cache
.It timeout
Debug timeouts
.It interface
Show interface, or vif, debug messages
.It groups
Debug group memberships
.It mtrace
Multicast traceroute information
.It igmp
Debug IGMP messages
.It icmp
Debug ICMP messages
.It rsrr
Debug RSRR messages
.El
.It Fl f, -foreground
Run in foreground, do not detach from calling terminal
.It Fl N, -disable-vifs
Disable all virtual interfaces (phyint) by default
.It Fl v, -version
Show
.Nm
version
.El

.Sh SIGNALS
.Nm
responds to the following signals:
.Pp
.Bl -tag -width TERM -compact
.It HUP
Restarts
.Nm .
The configuration file is reread every time this signal is evoked.
.It INT
Terminates execution gracefully (i.e. by sending
good-bye messages to all neighboring routers).
.It TERM
The same as INT.
.It USR1
Dumps the internal state of VIFs and multicast routing tables to
.Pa /var/tmp/pimd.dump .
.It USR2
Dumps the internal cache tables to
.Pa /var/tmp/pimd.cache .
.It QUIT
Dumps the internal routing tables to stderr (only if
.Nm
was invoked with a non-zero debug level).
.El
.Pp
For convenience in sending signals,
.Nm
writes its process ID to
.Pa /var/run/pimd.pid
upon startup.

.Sh FILES
.Bl -tag -width /var/tmp/pimd.cache -compact
.It Pa /etc/pimd.conf
.It Pa /var/tmp/pimd.cache
.It Pa /var/tmp/pimd.dump
.It Pa /var/run/pimd.pid
.El

.Sh SEE ALSO
.Xr mrouted 8 ,
.Xr smcroute 8 ,
.Xr /usr/share/doc/pimd/
.Pp
PIM-SM is described in, the now obsolete RFC 2362, and the current RFC 4601, with
additions in RFC 5059 and RFC 5796.
.Pp
The pages at USC, http://netweb.usc.edu/pim/, are unfortunately no longer available.
The wiki pages at http://github.com/troglobit/pimd/, the new GitHub project, are an
attempt to gather as much info as possible.

.Sh AUTHORS
.Nm
was written by Ahmed Helmy, George Edmond "Rusty" Eddy, and Pavlin Ivanov
Radoslavov.  With contributions by many others.
.Pp
This manual page was initially written by Antonín Král for the Debian GNU/Linux
system, it was later updated by Joachim Nilsson for the pimd project.
