.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PIMD 1 "March 27, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
pimd - PIMv2-SM multicast routing daemon
.SH SYNOPSIS
.B pimd
.RI [ options ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B pimd
program.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBpimd\fP provides implementation of Protocol Independent Multicast v2 protocol which is used in todays Internet for routing multicast traffic. PIM is widely deployed because it is main multicast routing protocol used in Cisco routers.
.SH The Protocol Independent Multicast--Sparse Mode (PIM-SM) architecture:
.TP
* maintains the traditional IP multicast service model of receiver-initiated membership;
.TP
* uses explicit joins that propagate hop-by-hop from members' directly connected routers toward the distribution tree.
.TP
* builds a shared multicast distribution tree centered at a Rendezvous Point, and then builds source-specific trees for those sources whose data traffic warrants it.
.TP
* is not dependent on a specific unicast routing protocol; and
.TP
* uses soft-state mechanisms to adapt to underlying network conditions and group dynamics.
.TP
The robustness, flexibility, and scaling properties of this architecture make it well suited to large heterogeneous internetworks.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For more informations see project documentation.
.TP
.B \-h, \-\-help
show brief information about usage
.TP
.B \-c FILE
pimd will use FILE as configuration file instead of /etc/pimd.conf
.TP
.B \-d LEVEL[,LEVEL]
add LEVEL to debugging. If you use -d \fBpimd\fP will not fork.
.SH SEE ALSO
.BR /usr/share/doc/pimd
.br
Directory with further reading.
.br
.BR http://netweb.usc.edu/pim/
.br
.BR http://netweb.usc.edu/pim/pimd/
.br
Project web pages.
.SH AUTHOR
This manual page was written by Antonín Král <A.Kral@sh.cvut.cz>,
for the Debian GNU/Linux system (but may be used by others).
